SELECT COUNT(*) FROM entity00;
SELECT COUNT(*) FROM entity00 WHERE type = 'PERSON';
SELECT COUNT(*) FROM entity00 WHERE type = 'ORG';
SELECT COUNT(*) FROM entity00 WHERE type = 'CARDINAL';
SELECT COUNT(*) FROM entity00 WHERE type = 'GPE';
