SELECT COUNT(*) FROM entity00 WHERE type IN ('NORP', 'PERSON', 'DATE', 'PRODUCT');
SELECT COUNT(*) FROM entity00 WHERE type = 'CARDINAL';
SELECT COUNT(*) FROM entity00 WHERE type != 'CARDINAL';
SELECT COUNT(*) FROM entity00 WHERE type IN ('CARDINAL', 'ORG', 'GPE', 'MONEY', 'WORK_OF_ART', 'PRODUCT');
SELECT COUNT(*) FROM entity00;