SELECT COUNT(*) FROM entity00 WHERE type IN ('NORP', 'PERSON', 'DATE', 'PRODUCT') ERROR_TARGET 5% CONFIDENCE 95%
SELECT COUNT(*) FROM entity00 WHERE type = 'CARDINAL' ERROR_TARGET 5% CONFIDENCE 95%
SELECT COUNT(*) FROM entity00 WHERE type != 'CARDINAL' ERROR_TARGET 5% CONFIDENCE 95%
SELECT COUNT(*) FROM entity00 WHERE type IN ('CARDINAL', 'ORG', 'GPE', 'MONEY', 'WORK_OF_ART', 'PRODUCT') ERROR_TARGET 5% CONFIDENCE 95%
SELECT COUNT(*) FROM entity00 ERROR_TARGET 5% CONFIDENCE 95%