SELECT SUM(entity_start) FROM entity00 ERROR_TARGET 5% CONFIDENCE 95%;
SELECT COUNT(*) FROM entity00 WHERE entity_start >= 6 ERROR_TARGET 5% CONFIDENCE 95%;
SELECT COUNT(*) FROM entity00 WHERE entity_start >= 13 ERROR_TARGET 5% CONFIDENCE 95%;
SELECT COUNT(*) FROM entity00 WHERE entity_start >= 23 ERROR_TARGET 5% CONFIDENCE 95%;
SELECT COUNT(*) FROM entity00 WHERE entity_start >= 36 ERROR_TARGET 5% CONFIDENCE 95%;
