SELECT SUM(entity_start) FROM entity00  ERROR_TARGET 1% CONFIDENCE 95%;
SELECT SUM(entity_start) FROM entity00  ERROR_TARGET 2.5% CONFIDENCE 95%;
SELECT SUM(entity_start) FROM entity00  ERROR_TARGET 5% CONFIDENCE 95%;
SELECT SUM(entity_start) FROM entity00  ERROR_TARGET 7.5% CONFIDENCE 95%;
SELECT SUM(entity_start) FROM entity00  ERROR_TARGET 10% CONFIDENCE 95%;