name: Run Tests

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version to run the tests'
        default: 3.11
        required: false
        type: float
  # push:
  #   branches: [ main ]
  # pull_request:
  #   types: [ opened, synchronize, reopened ]

env:
  AIDB_NUMBER_OF_TEST_RUNS: 2

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: testaidb
        ports:
          - 3306:3306

      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: testaidb
        ports:
          - 5432:5432

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ github.event.inputs.python_version }}  # Specify the Python version you need

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download test data
      run: git clone https://github.com/ttt-77/AIDB_data.git tests/data

    - name: Run db setup tests
      run: python3 -m tests.tests_db_setup

    - name: Run inference config tests
      run: python3 -m tests.tests_inference_config_validity

    - name: Run query columns test
      run: python3 -m tests.tests_columns_in_query

    - name: Run full scan tests
      run: python3 -m tests.tests_full_scan_engine

    - name: Run limit engine tests
      run: python3 -m tests.test_limit_engine

    - name: Run caching logic tests
      run: python3 -m tests.tests_caching_logic

    - name: Run data store tests
      run: python3 -m tests.tests_data_store

    - name: Run vector database setup tests
      run: python3 -m tests.tests_vector_database_setup

    - name: Run query parser tests
      run: python3 -m tests.test_queries

    - name: Run exact aggregation query tests
      run: python3 -m tests.test_exact_aggregation

    - name: Run Twitter Full Scan Tests
      run: python3 -m tests.tests_full_scan_engine_twitter

    - name: Run Full Scan Tests for nested queries
      run: python3 -m tests.tests_full_scan_nested_query

    - name: Run Full Scan Tests for udf queries
      run: python3 -m tests.tests_full_scan_engine_udf

    - name: Run Query Parsing Tests for nested queries
      run: python3 -m tests.test_query_parsing

    - name: Run aggregation query Gaussian tests
      run: python3 -m tests.test_aggregation_gaussian

    - name: Run aggregation query Gaussian multiple keys tests
      run: python3 -m tests.test_aggregation_gaussian_mk

    - name: Run approx aggregation join query tests
      run: python3 -m tests.test_aggregation_join
      
    - name: Run aggregation query tests
      run: python3 -m tests.test_aggregation

