name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the Python version you need

    - name: Install dependencies
      run: | 
        pip install -r requirements.txt
        find requirements/*/ -name "requirements-*.txt" -print0 | xargs -0 -I {} pip install -r {}

    - name: Download test data
      run: |
        gdown https://drive.google.com/uc?id=18H5tzgx6LfEb7ykOg1XUuZCmhLP1Wiy8
        unzip data.zip -d tests/

    - name: Run db setup tests
      run: python3 -m tests.tests_db_setup

    - name: Run inference config tests
      run: python3 -m tests.tests_inference_config_validity

    - name: Run query columns test
      run: python3 -m tests.tests_columns_in_query

    - name: Run full scan tests
      run: python3 -m tests.tests_full_scan_engine

    - name: Run limit engine tests
      run: python3 -m tests.test_limit_engine

    - name: Run caching logic tests
      run: python3 -m tests.tests_caching_logic

    - name: Run data store tests
      run: python3 -m tests.tests_data_store

    - name: Run vector database setup tests
      run: python3 -m tests.tests_vector_database_setup

    - name: Run query parser tests
      run: python3 -m tests.test_queries

    - name: Run exact aggregation query tests
      run: python3 -m tests.test_exact_aggregation

    - name: Run Twitter Full Scan Tests
      run: python3 -m tests.tests_full_scan_engine_twitter

    - name: Run Full Scan Tests for nested queries
      run: python3 -m tests.tests_full_scan_nested_query

    - name: Run Query Parsing Tests for nested queries
      run: python3 -m tests.test_query_parsing

    # - name: Run aggregation query tests
    #   run: python3 -m tests.test_aggregation

    # - name: Run aggregation query Gaussian tests
    #   run: python3 -m tests.test_aggregation_gaussian

    # - name: Run aggregation query Gaussian multiple keys tests
    #   run: python3 -m tests.test_aggregation_gaussian_mk
