name: Run Tests

on:
  push: {}  # Remove the branch restriction to trigger the workflow for any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the Python version you need

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download test data
      run: |
        gdown https://drive.google.com/uc?id=1QKKj99s01qoL-kpNfcoYUBTY3TyPML9f
        unzip data.zip -d tests/

    - name: Run db setup tests
      run: python3 -m tests.tests_db_setup

    - name: Run inference config tests
      run: python3 -m tests.tests_inference_config_validity

    - name: Run query columns test
      run: python3 -m tests.tests_columns_in_query

    - name: Run full scan tests
      run: python3 -m tests.tests_full_scan_engine

    - name: Run limit engine tests
      run: python3 -m tests.test_limit_engine

    - name: Run caching logic tests
      run: python3 -m tests.tests_caching_logic

    - name: Run data store tests
      run: python3 -m tests.tests_data_store

    - name: Run vector database setup tests
      run: python3 -m tests.tests_vector_database_setup

    - name: Run query parser tests
      run: python3 -m tests.test_queries

    - name: Run exact aggregation query tests
      run: python3 -m tests.test_exact_aggregation

    # - name: Run aggregation query Avg tests
    #   run: python3 -m tests.test_aggregation

    # - name: Run aggregation query Avg Gaussian tests
    #   run: python3 -m tests.test_aggregation_gaussian
